/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: '#F7F7F5',
        surface: '#FFFFFF',
        border: '#E3E3DF',
        'border-strong': '#C9C9C3',
        text: '#1A1A1A',
        muted: '#6B6B66',
        faint: '#9C9C96',
        accent: '#4F4CE8',
        'accent-soft': '#EEEEFB',
        warn: '#C9861A',
        'warn-soft': '#FBF3E1',
        danger: '#C13B3B',
        'danger-soft': '#FBEAEA',
        ok: '#3B8F5C',
        'ok-soft': '#E8F3EC',
        flag: '#2B5FA7',
        'flag-soft': '#E6EEF9',
        lien: '#8A4AA6',
        'lien-soft': '#F1E8F5',
      },
      fontFamily: {
        sans: ['system-ui', '-apple-system', 'Helvetica Neue', 'Hiragino Sans', 'Noto Sans JP', 'sans-serif'],
        mono: ['ui-monospace', 'Menlo', 'monospace'],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '1.4' }],
        xs: ['12px', { lineHeight: '1.5' }],
        sm: ['13px', { lineHeight: '1.5' }],
        base: ['14px', { lineHeight: '1.5' }],
        md: ['15px', { lineHeight: '1.5' }],
        lg: ['16px', { lineHeight: '1.5' }],
        xl: ['18px', { lineHeight: '1.4' }],
        '2xl': ['20px', { lineHeight: '1.3' }],
        '3xl': ['24px', { lineHeight: '1.2' }],
        '4xl': ['28px', { lineHeight: '1.2' }],
        '5xl': ['38px', { lineHeight: '1.1' }],
      },
      borderRadius: {
        sm: '6px',
        DEFAULT: '8px',
        md: '10px',
        lg: '12px',
        xl: '14px',
      },
      spacing: {
        sidenav: '88px',
        status: '24px',
        'btn-md': '52px',
        'btn-lg': '60px',
      },
      width: {
        sidenav: '88px',
      },
    },
  },
  plugins: [],
}
